### ISSUE TITLE
FE styling FP/toolbox

### ISSUE THREAD

**Issue by sales-beamery** [SeedJobs/git-beam-it#2]
![Screen Shot 2017-08-09 at 11:10 AM](http://marker.screenshots.prod.s3.amazonaws.com/0e5d5738df8642018b205e621dfc9dad-1502277044653.png)

(added by Slava)

See Image

---
### More Info

**Source URL**: [https://app.beamery.com/#/candidates/vacancy/f4758970-0086-49cd-ab7f-b6b1b96360f9](https://app.beamery.com/#/candidates/vacancy/f4758970-0086-49cd-ab7f-b6b1b96360f9)

<table><tr><td><strong>Browser</strong></td><td>Chrome 59.0.3071.115</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1627 x 1053</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.6</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</td></tr></table>

**Comment by slava-tre** [comment]
Issue moved to [SeedJobs/team_CRM #380](https://github.com/SeedJobs/team_CRM/issues/380) via [**ZenHub**](https://www.zenhub.com/)
